# config/_default/menus.toml

[[main]]
name = "Top"
url = "/"
weight = -200

[[main]]
name = "Blog"
url = "/posts/"
weight = 10

[[main]]
name = "Docs"
url = "/docs/"
weight = 10

[[main]]
name = "Intro"
url = "/intro/"
weight = 10

[[main]]
name = "Topics"
url = "/topics/"
weight = 20

[[footer]]
name = "p.p."
url = "/privacypolicy"
