# config/_default/menus.toml

[[main]]
name = "Top"
pageRef = "/ja"
weight = -200

[[main]]
name = "Blog"
url = "/ja/posts/"
weight = 10

[[main]]
name = "Docs"
url = "/ja/docs/"
weight = 10

[[main]]
name = "Intro"
url = "/intro/"
weight = 10

[[main]]
name = "Topics"
url = "/ja/topics/"
weight = 20

[[footer]]
name = "p.p."
url = "/ja/privacypolicy"
