# config/_default/menus.toml

[[main]]
name = "Top"
url = "/"
weight = -200

[[main]]
name = "Docs"
url = "/docs/"
weight = 10

[[main]]
name = "Intro"
url = "/intro/"
weight = 10

[[footer]]
name = "p.p."
url = "/privacypolicy"
