version: '3'

services:
  nvim:
    build:
      context: ./playground/linux
    tty: true
  docsserver:
    image: klakegg/hugo:0.107.0
    command: server
    volumes:
      - .:/src
    ports:
      - 1313:1313
