gui:
  language: en
  nerdFontsVersion: "3"
git:
  merging:
    args: "--no-ff"
  paging:
    colorArg: always
    # pager: delta --dark --paging=never
    pager: diff-so-fancy
customCommands:
  - key: "C"
    context: "files"
    command: "git commit -v"
    description: "Commit changes using git editor"
    subprocess: true
