gui:
  language: en
  nerdFontsVersion: "3"
  theme:
    inactiveBorderColor:
      - "#777777"
git:
  merging:
    args: "--no-ff"
  pagers:
    - colorArg: always
      # pager: delta --dark --paging=never
      pager: diff-so-fancy
  overrideGpg: true
customCommands:
  - key: "C"
    context: "files"
    command: "git commit -v"
    description: "Commit changes using git editor"
    output: terminal
  - key: "L"
    command: "tig --all"
    context: "localBranches"
    output: terminal
