# ~/.config/mise/config.toml

[tasks.cargo-build]
description = "Build the Rust project using Cargo"
run = "cargo build --release"

[tasks.open]
description = "mise wo hirogeru"
run = "echo 'OPEN SESAME!'"

[tools]
"aqua:anthropics/claude-code" = { version = "latest", os = ["linux", "macos"] }
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:openai/codex" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/numbat" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:astral-sh/uv" = "latest"
"cargo:git-bahn/git-graph" = "latest"
"go:github.com/x-motemen/ghq" = "latest"
"npm:ccusage" = "latest"
"npm:node-gyp-build" = "latest"
"npm:zenn-cli" = "latest"
go = "latest"
gradle = "latest"
java = "latest"
node = "latest"
npm = "latest"
pnpm = "latest"
python = "latest"
"github:k1LoW/mo" = "latest"
"github:ShortArrow/runex" = "0.1.14"

[tool_alias]
python3 = "python"

[tool_alias.python]

[tool_alias.python.versions]
python3 = "python"
