# ~/.config/mise/config.toml

[tasks.cargo-build]
description = "Build the Rust project using Cargo"
run = "cargo build --release"

[tasks.open]
description = "mise wo hirogeru"
run = "echo 'OPEN SESAME!'"

[tools]
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/numbat" = "latest"
"aqua:astral-sh/uv" = "latest"
"cargo:git-bahn/git-graph" = "latest"
"cargo:sharkdp/bat" = "latest"
go = "latest"
"go:github.com/x-motemen/ghq" = "latest"
gradle = "latest"
java = "latest"
node = "latest"
npm = "latest"
"npm:@google/gemini-cli" = "latest"
pnpm = "latest"
python = "latest"

[tool_alias]
python3 = "python"

[tool_alias.python]

[tool_alias.python.versions]
python3 = "python"
