Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  # VirtualBox config
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]  # Enable 3D accelaration
    v.customize ["modifyvm", :id, "--vram", "128"]        # Set 128MB video memory size
    v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]  # Set VMSVGA graphic controller
  end

  # Provision
  config.vm.provision "shell", privileged: false, path: "./provision.sh"
end
