#!/usr/bin/env bash
# Regenerate assets/css/syntax.css.
#
# markup.toml sets `noClasses = false`, so Chroma emits class names and the
# colours have to come from a stylesheet. Chroma can only produce one theme per
# run, so this builds two and scopes the dark one to the same selectors the
# design tokens use — media query for "follow the OS", data-theme for "the
# reader chose".
#
# The generated background rules are dropped: the code block takes its
# background from --bg-sunken so it matches the rest of the page in both
# appearances.
set -euo pipefail

cd "$(dirname "$0")/.."

LIGHT_STYLE=github
DARK_STYLE=github-dark
OUT=assets/css/syntax.css

emit() {
  hugo gen chromastyles --style="$1" |
    grep -v '^/\* Generated using' |
    grep -v '^/\* Background \*/' |
    sed -e 's/^\(\/\* PreWrapper \*\/ \.chroma {\)[^}]*}/\1 }/' |
    grep -v '^$'
}

{
  echo "/* Syntax highlighting — generated by scripts/gen-syntax-css.sh."
  echo "   Do not edit. Light: $LIGHT_STYLE. Dark: $DARK_STYLE. */"
  echo
  emit "$LIGHT_STYLE"
  echo
  echo '@media (prefers-color-scheme: dark) {'
  emit "$DARK_STYLE" | sed -e 's/\.chroma/:root:not([data-theme="light"]) .chroma/g' -e 's/^/  /'
  echo '}'
  echo
  emit "$DARK_STYLE" | sed -e 's/\.chroma/:root[data-theme="dark"] .chroma/g'
} >"$OUT"

echo "wrote $OUT ($(wc -l <"$OUT") lines)"
